name: Listening S3 Buckets

on:
  push:
    branches:
      - master

  workflow_dispatch:


jobs:
  listening_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.IAM}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: List S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION}}
        run: |
          echo "Listing S3 Buckets in region $AWS_REGION"
          aws s3 ls